FROM python:3.12.10-slim-bullseye
ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /app

COPY requirements.cpu.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt --extra-index-url https://download.pytorch.org/whl/cpu

ENV HF_ENABLE_HF_TRANSFER=1
EXPOSE 8000
COPY server.py /app
CMD ["python", "/app/server.py"]
